Aoi1591/SHYAK

CSS/main.css
=> background

PHP/header.php
font awesomeのリンクを貼っているだけのヘッダーです。ヘッダーのタグを閉じていないので、必要なリンクがあれば各ページで追加して呼んであげてください。もしかしたら後でcssのリンクとか追加するかも
=> header.phpを作成しました

SHYAK/JavaScript/hamburger.js, SHYAK/PHP/menu-hamburger.php
ハンバーガーメニューのコメント、メニュー内のリンクの追加を行った。
=> コメントアウト、リンクの追加

SHYAK/PHP/Choose your language.php, SHYAK/PHP/Chooseyourlanguage.php
=> Choose your language

SHYAK/PHP/top.php
CSS読み込んだらハンバーガー表示されないかなって淡い期待をかけてみる
=> CSS読み込ませてみる

SHYAK/PHP/login-output.php
一応これでログインできると思う。セッションの指定なんかもしているので、セッション情報使いたいときここ見て
=> login-output.php

SHYAK/PHP/menu-humburger.php
=> ハンバーガーメニュー

SHYAK/PHP/login-output.php, SHYAK/PHP/signup-output.php
なんかちょいちょいミスってるとこあったからその修正と、新規登録のバックを作成しました。
=> ログインのバックの修正、サインアップのバック作成

SHYAK/PHP/AdminLogin-check.php, SHYAK/PHP/AdminLogin-input.php, SHYAK/PHP/header.php, SHYAK/PHP/login-output.php, SHYAK/PHP/secretQuestion.php
管理者用ログインページへ飛ばすために秘密の質問させるページの準備とか！
=> 管理者用ログインの準備など

SHYAK/JavaScript/signup-input.js, SHYAK/PHP/login-input.php, SHYAK/signup-input.php
=> Login　Signup

SHYAK/PHP/Choose your language.php, SHYAK/PHP/top.php
トップページのメニュー的なやつを英訳できるよう期待を込めました。
=> topページの英訳チャレンジ

SHYAK/PHP/Binnagasu-output.php, SHYAK/PHP/Chooseyourlanguage.php, SHYAK/PHP/Explanationofrules.php
ルール説明に翻訳あてたのと、言語設定が大文字になってたのを小文字に変更しました
=> ルール説明の英訳化、言語指定の変更

SHYAK/JavaScript/pass-check.js, SHYAK/PHP/signup-input.php
フォームの送信をVueに一任してるからその記述と、Vue内のタイプミスを修正した
=> Vue処理をうまく作動させるための修正

SHYAK/JavaScript/pass-check.js, SHYAK/PHP/signup-output.php
=> 送信データをPOSTに変更

SHYAK/PHP/friend-request.php, SHYAK/PHP/login-output.php
=> うまくいくといいけど

SHYAK/CSS/login-input.css, SHYAK/CSS/logout.css
=> ログアウトのcss作成

SHYAK/PHP/Choose your language.php
選択した拾う瓶の言語ごとに確認ページで国旗画像を表示
今んとこポルトガルはないよー
=> Update Choose your language.php

SHYAK/PHP/login-output.php
=> login-output修正

SHYAK/CSS/mypage.css, SHYAK/JavaScript/mypage.js, SHYAK/PHP/mypage-connect.php, SHYAK/PHP/mypage.php
マイページ更新できるところまで修正しています。
コード読み取っての取り急ぎの修正になるので、
間違いがあったら教えてください！！！
↓動作確認
=> Hiroshi tsudaのいろいろな修正

SHYAK/CSS/top.css, SHYAK/PHP/UserPage-output.php, SHYAK/PHP/UserPage.php, SHYAK/PHP/top.php
=> フレンドブロック申請
